# Generated by Django 5.2.4 on 2026-06-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                ("costoUnitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("nacionalidad", models.CharField(max_length=50)),
                ("sexo", models.CharField(max_length=20)),
                ("documento", models.CharField(max_length=20)),
                ("boleta", models.CharField(max_length=30)),
                ("categoria", models.CharField(max_length=50)),
                ("categoriaTexto", models.CharField(max_length=100)),
                ("producto", models.CharField(max_length=100)),
                ("explicacion", models.TextField()),
                (
                    "evidenciaNombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "evidenciaTipo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("evidenciaBase64", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("progreso", "En progreso"),
                            ("resuelto", "Resuelto"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="progreso",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "estado_visual",
                    models.CharField(
                        choices=[
                            ("baja", "Prioridad baja"),
                            ("media", "Prioridad media"),
                            ("urgente", "Urgente"),
                            ("revision", "En revisión"),
                            ("resuelto", "Resuelto"),
                        ],
                        default="revision",
                        max_length=20,
                    ),
                ),
                ("comentarioSupervisor", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("supervisor", "Supervisor"),
                            ("tecnico", "Técnico"),
                            ("vendedor", "Vendedor"),
                            ("gerente", "Gerente"),
                            ("cliente", "Cliente"),
                        ],
                        default="cliente",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformeTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nombreAsistido", models.CharField(max_length=100)),
                ("apellidoAsistido", models.CharField(max_length=100)),
                ("explicacion", models.TextField()),
                (
                    "correccion",
                    models.CharField(
                        choices=[("si", "Sí"), ("parcial", "Parcial"), ("no", "No")],
                        max_length=20,
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="api.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtencionVendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nombreCliente", models.CharField(max_length=100)),
                ("apellidoCliente", models.CharField(max_length=100)),
                ("notas", models.TextField()),
                (
                    "montoCobro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("detalleCobro", models.CharField(blank=True, max_length=255)),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atenciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticketRelacionado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ticket",
                    ),
                ),
            ],
        ),
    ]
