# Generated by Django 5.2.4 on 2026-06-18 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boleta", models.CharField(max_length=30, unique=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nombreCliente", models.CharField(max_length=100)),
                ("apellidoCliente", models.CharField(max_length=100)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("productos", models.JSONField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("activa", "Activa"), ("anulada", "Anulada")],
                        default="activa",
                        max_length=20,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
