# Generated by Django 5.2.4 on 2026-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_venta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("supervisor", "Supervisor"),
                    ("tecnico", "Técnico"),
                    ("vendedor", "Vendedor"),
                    ("gerente", "Gerente"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
